version: '3.8'
services:
  postgres:
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_PASSWORD: wellwave123
      POSTGRES_DB: wellwavedb
      POSTGRES_USER: wellwave
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nestjs-app
    container_name: nestjs-app
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=wellwave
      - POSTGRES_PASSWORD=wellwave123
      - POSTGRES_DATABASE=wellwavedb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    
volumes:
  postgres-data:
    driver: local