version: '3.8'
services:
  postgres:
    image: postgres:16.3
    container_name: wellwave-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DATABASE
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: root@wellwave.com
      PGADMIN_DEFAULT_PASSWORD: wellwave123
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
  
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nestjs-app
    container_name: wellwave-nestjs
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DATABASE=$POSTGRES_DATABASE
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    
volumes:
  pgadmin-data:
    driver: local
  postgres-data:
    driver: local