version: '3.8'
services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wellwave123
      MYSQL_DATABASE: wellwavedb
      MYSQL_USER: wellwave
      MYSQL_PASSWORD: wellwave123
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local
