# version: '3.8'
services:
  postgres:
    image: postgres:16.3
    container_name: wellwave-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DATABASE
      POSTGRES_USER: $POSTGRES_USER
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nestjs-app
    container_name: wellwave-nestjs
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DATABASE=$POSTGRES_DATABASE
    # volumes:
    #   - .:/usr/src/app
    #   - /usr/src/app/node_modules
    command: npm run start:dev
    
volumes:
  postgres-data:
    driver: local